monitoring/app/urls.py
from django.urls import path
from .views import index, login_view, control, author, test_page, add_results, edit_users, \
    get_exercises_for_category, get_exercise_standard, get_cadets_from_dep, save_grading_data, edit_groups, \
    update_group, delete_group, delete_user, update_user, editing_page, get_editing_table, save_new_obj, delete_object,\
    update_object, get_leaderboards, get_user_data
from .views import edit_platoons, update_platoon, delete_platoon, edit_companies, update_company, delete_company,\
    edit_faculty, update_faculty, delete_faculty, report
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='app:login'), name='logout'),
    path('control/', control, name='control'),

    path('author/', author, name='author'),
    path('test_page/', test_page, name='test_page'),
    path('edit_users/', edit_users, name='edit_users'),
    path('update_user/<int:pk>/', update_user, name='update_user'),
    path('delete_user/<int:pk>/', delete_user, name='delete_user'),
    path('edit_groups/', edit_groups, name='edit_groups'),
    path('update_group/<int:pk>/', update_group, name='update_group'),
    path('delete_group/<int:pk>/', delete_group, name='delete_group'),

    path('edit_platoons/', edit_platoons, name='edit_platoons'),
    path('update_platoon/<int:pk>/', update_platoon, name='update_platoon'),
    path('delete_platoon/<int:pk>/', delete_platoon, name='delete_platoon'),

    path('edit_companies/', edit_companies, name='edit_companies'),
    path('update_company/<int:pk>/', update_company, name='update_company'),
    path('delete_company/<int:pk>/', delete_company, name='delete_company'),

    path('edit_faculty/', edit_faculty, name='edit_faculty'),
    path('update_faculty/<int:pk>/', update_faculty, name='update_faculty'),
    path('delete_faculty/<int:pk>/', delete_faculty, name='delete_faculty'),

    path('editing_page/', editing_page, name='editing_page'),
    path('get_editing_table/', get_editing_table, name='get_editing_table'),
    path('save_new_obj/', save_new_obj, name='save_new_obj'),
    path('delete_object/<str:obj>/<int:pk>/', delete_object, name='delete_object'),
    path('update_object/<str:obj>/<int:pk>/', update_object, name='update_object'),

    path('add_results/', add_results, name='add_results'),
    path('get_exercises_for_category/<int:category_id>/',
         get_exercises_for_category, name='get_exercises_for_category'),
    path('get_exercise_standard/<int:exercise_id>/<int:departament_id>/<int:uniform_id>/',
         get_exercise_standard, name='get_exercise_standard'),
    path("get_cadets_from_dep/<int:departament_id>/",
         get_cadets_from_dep, name='get_cadets_from_dep'),
    path('save_grading_data/', save_grading_data, name='save_grading_data'),

    path('get_leaderboards/', get_leaderboards, name='get_leaderboards'),
    path('get_user_data/<int:pk>/', get_user_data, name='get_user_data'),

    path('report/', report, name='report'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monitoring/monitoring/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
handler404 = 'app.views.page_not_found_view'

monitoring/app/forms.py
from django import forms
from .models import Category, Exercise, Departament, AbsenceReason, Cadet, Uniforms, Platoon, Company, Faculty
from datetime import date

class SetCategoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      empty_label=None,
                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                      label="Категория")

    class Meta:
        model = Category
        fields = ['category']


class SetExerciseForm(forms.ModelForm):
    exercise = forms.ModelChoiceField(
        queryset=Exercise.objects.none(),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Упражнение"
    )

    class Meta:
        model = Exercise
        fields = ['exercise']


class SetDepartamentForm(forms.ModelForm):
    departament = forms.ModelChoiceField(
        queryset=Departament.objects.all(),
        required=True,
        empty_label=None,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Направление"
    )

    class Meta:
        model = Departament
        fields = ['departament']


class SetAbsenceForm(forms.ModelForm):
    absence = forms.ModelChoiceField(
        queryset=AbsenceReason.objects.all(),
        empty_label='',
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Причина отсутствия",
        required=False)

    class Meta:
        model = AbsenceReason
        fields = ['absence']


class SetCadetResultForm(forms.ModelForm):
    class Meta:
        model = Cadet
        fields = ['name']

    result = forms.FloatField()


class SetUniformForm(forms.ModelForm):
    uniforms = forms.ModelChoiceField(
        queryset=Uniforms.objects.all(),
        empty_label=None,
        widget=forms.Select(attrs={'class': 'form-control'}),
        label="Тип формы",
        required=False)

    class Meta:
        model = Uniforms
        fields = ['uniforms']


class EditDepartamentForm(forms.ModelForm):
    class Meta:
        model = Departament
        fields = '__all__'
        labels = {
            "name": "Название",
            "platoon": "Взвод",
            "course": "Курс"
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class EditPlatoonForm(forms.ModelForm):
    class Meta:
        model = Platoon
        fields = '__all__'
        labels = {
            "name": "Название",
            "company": "Направление",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class EditCompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        labels = {
            "name": "Название",
            "faculty": "Факультет",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class EditFacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty
        fields = '__all__'
        labels = {
            "name": "Название",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class EditCadetForm(forms.ModelForm):
    class Meta:
        model = Cadet
        fields = '__all__'
        labels = {
            "name": "Имя",
            "surname": "Фамилия",
            "patronymic": "Отчество",
            "rank": "Звание",
            "departament": "Отделение",
            "course": "Курс",
            "photo": "Фотография"
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class FilterForm(forms.Form):
    categories = Category.objects.all()

    # Создаем список кортежей в формате ('значение', 'отображаемое_название')
    category_choices = [(category.id, category.name) for category in categories]

    name = forms.CharField(required=True, label='ФИО',
                           widget=forms.TextInput(attrs={'class': 'form-control mr-2', 'placeholder': 'Начните вводить имя'}),
                           error_messages={'required': 'Пожалуйста, заполните поле "ФИО".'})
    discipline = forms.ChoiceField(
        choices=category_choices,
        label='Дисциплина',
        widget=forms.Select(attrs={'class': 'form-control mr-2'})
    )
    start_date = forms.DateField(label='Время (с)',
                                 widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control mr-2'}))
    end_date = forms.DateField(label='Время (по)',
                               widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control mr-2'}))


class FilterFormLoadFile(forms.Form):
    categories = Category.objects.all()
    category_choices = [(category.id, category.name) for category in categories]
    category_choices.insert(0, ('all', 'Все'))

    name = forms.CharField(required=True, label='ФИО',
                           widget=forms.TextInput(
                               attrs={'class': 'form-control mr-2', 'placeholder': 'Начните вводить имя'}),
                           error_messages={'required': 'Пожалуйста, заполните поле "ФИО".'})
    discipline = forms.ChoiceField(
        choices=category_choices,
        label='Дисциплина',
        widget=forms.Select(attrs={'class': 'form-control mr-2'})
    )
    start_date = forms.DateField(label='Время (с)',
                                 widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control mr-2'}))
    end_date = forms.DateField(label='Время (по)',
                               widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control mr-2'}))

monitoring/app/templates/author.html
{% extends 'base.html' %}

{% block title %}Author Page{% endblock %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row m-1">
        <div class="col-md-4">
            <img src="{% static 'img/author1.jpg' %}" alt="Author Photo" class="img-fluid rounded">
        </div>
        <div class="col-md-8">
            <h2 class="mb-4">Кручинина Кристина Сергеевна</h2>
            <p class="lead">Мастер спорта России по  рукопашному бою.</p>
        </div>
    </div>
    <div class="row m-1">
        <div class="col-md-4">
            <img src="{% static 'img/author2.jpg' %}" alt="Author Photo" class="img-fluid rounded">
        </div>
        <div class="col-md-8">
            <h2 class="mb-4">Пак Павел Сергеевич</h2>
            <p class="lead">Председатель спортивного комитета Росгвардии.</p>
        </div>
    </div>
</div>
{% endblock %}

monitoring/app/templates/control.html
{% extends 'base.html' %}

{% block title %}Control Page{% endblock %}

{% block content %}
<div class="container mt-5 text-center">
    <h2 class="mb-4">Контроль результатов</h2>

    <!-- Filters -->
    <form class="form-inline mb-4 text-center" method="post" action="{% url 'app:control' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" id="id_name_hidden" name="name_hidden">
    <button type="submit" class="btn btn-primary mt-2">Применить</button>
    </form>
</div>


<div class="container text-center">
    {% if datas %}
        {% for d in datas %}
        <h6 class="mb-4">{{ d.exercise_name }}</h6>
        <div class="row">
            <canvas id="myChartScatter{{ forloop.counter }}"></canvas>
        </div>
        {% endfor %}
    {% else %}
        <p>Данных по заданному имени не найдено.</p>
    {% endif %}
</div>

{% for d in datas %}
    <script>
        var ctx{{ forloop.counter }} = document.getElementById('myChartScatter{{ forloop.counter }}').getContext('2d');
        var myChart{{ forloop.counter }} = new Chart(ctx{{ forloop.counter }}, {
            type: 'line',
            data: {
                datasets: [
                    {% for table in d.data %}
                    {
                        label: '{{table.uniform_name}}',
                        data: [
                                {% for res in table.data %}
                                    {x: '{{res.x}}', y: {{res.y}}},
                                {% endfor %}
                            ],
                    },
                    {% endfor %}
                ]
            },
            options: {
              plugins: {
                title: {
                  text: '{{ d.exercise_name }}',
                  display: false
                }
              },
              scales: {
                x: {
                  type: 'time',
                  time: {
                    unit: 'day'
                  },
                  title: {
                    display: true,
                    text: 'Дата'
                  },
                },
                y: {
                  title: {
                    display: true,
                    text: 'Значение'
                  }
                }
              }
            },
        });
    </script>
{% endfor %}



<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Получаем элементы по ID
    var endDateInput = document.getElementById('id_end_date');
    var startDateInput = document.getElementById('id_start_date');

    // Проверяем наличие элементов и отсутствие значений
    if (endDateInput && !endDateInput.value) {
      var currentDate = new Date();
      // Устанавливаем значение только в случае отсутствия текущего значения
      endDateInput.value = currentDate.toISOString().split('T')[0];
    }

    if (startDateInput && !startDateInput.value) {
      var currentDate = new Date();
      var startDate = new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1);
      // Устанавливаем значение только в случае отсутствия текущего значения
      startDateInput.value = startDate.toISOString().split('T')[0];
    }
  });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_name").autocomplete({
            source: '{% url 'app:control' %}',
            minLength: 2,
            select: function(event, ui) {
                event.preventDefault();
                $("#id_name").val(ui.item.label);
                $("#id_name_hidden").val(ui.item.value); // Скрытое поле для хранения cadet.pk
            }
        }).autocomplete("widget").addClass("custom-bootstrap-autocomplete");
    });
</script>
{% endblock %}

monitoring/app/templates/edit_companies.html
{% extends 'base.html' %}

{% block title %}Edit companies Page{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% if success %}
            <div class="alert alert-success" role="alert">
                Направление добавлено
            </div>
        {% endif %}
        {% if success_update %}
            <div class="alert alert-success" role="alert">
                Запись обновлена
            </div>
        {% endif %}
    </div>
    <div class="row">
        <h2 class="mt-4 text-center">Редактирование направлений</h2>
        {% if update %}
            <form id="update_data" method="post">
                    {% csrf_token %}
                    {{form}}
            </form>
        <div>
            <button form="update_data" type="submit" class="btn btn-primary mt-5">Обновить</button>
            <a href="/edit_platoons/" class="btn btn-secondary mt-5">Назад</a>
        </div>

        {% else %}
            <button type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#exampleModal">
              Добавить новое направление
            </button>
            <table class="table table-bordered mt-4">
                <thead>
                <tr>
                  <th scope="col">id</th>
                  <th scope="col">Название</th>
                  <th scope="col">Факультет</th>
                  <th scope="col" style="width: 50px;">Действие</th>
                </tr>
              </thead>
                <tbody>
            {% for i in departaments %}
            <tr>
              <th>{{i.id}}</th>
              <td>{{i.name}}</td>
              <td>{{i.faculty}}</td>
              <td scope="col">
                  <div class="container">
                      <div class="row">
                            <div class="col-md-6">
                                <a href="{% url 'app:update_company' i.id %}"><i class="fas fa-pencil-alt"></i></a>
                            </div>
                            <div class="col-md-6">
                                <a href="{% url 'app:delete_company' i.id %}"><i class="fas fa-trash"></i></a>
                            </div>
                      </div>
                  </div>
              </td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        {% endif %}

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Новое направление</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form id="add_form" method="post">
                    {% csrf_token %}
                    {{form}}
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

monitoring/app/templates/edit_faculty.html
{% extends 'base.html' %}

{% block title %}Edit faculty Page{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% if success %}
            <div class="alert alert-success" role="alert">
                Факультет добавлен
            </div>
        {% endif %}
        {% if success_update %}
            <div class="alert alert-success" role="alert">
                Запись обновлена
            </div>
        {% endif %}
    </div>
    <div class="row">
        <h2 class="mt-4 text-center">Редактирование факультетов</h2>
        {% if update %}
            <form id="update_data" method="post">
                    {% csrf_token %}
                    {{form}}
            </form>
        <div>
            <button form="update_data" type="submit" class="btn btn-primary mt-5">Обновить</button>
            <a href="/edit_faculty/" class="btn btn-secondary mt-5">Назад</a>
        </div>

        {% else %}
            <button type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#exampleModal">
              Добавить новый факультет
            </button>
            <table class="table table-bordered mt-4">
                <thead>
                <tr>
                  <th scope="col">id</th>
                  <th scope="col">Название</th>
                  <th scope="col" style="width: 50px;">Действие</th>
                </tr>
              </thead>
                <tbody>
            {% for i in departaments %}
            <tr>
              <th>{{i.id}}</th>
              <td>{{i.name}}</td>
              <td scope="col">
                  <div class="container">
                      <div class="row">
                            <div class="col-md-6">
                                <a href="{% url 'app:update_faculty' i.id %}"><i class="fas fa-pencil-alt"></i></a>
                            </div>
                            <div class="col-md-6">
                                <a href="{% url 'app:delete_faculty' i.id %}"><i class="fas fa-trash"></i></a>
                            </div>
                      </div>
                  </div>
              </td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        {% endif %}

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Новый факультет</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form id="add_form" method="post">
                    {% csrf_token %}
                    {{form}}
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

monitoring/app/templates/edit_groups.html
{% extends 'base.html' %}

{% block title %}Edit groups Page{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% if success %}
            <div class="alert alert-success" role="alert">
                Отделение добавлено
            </div>
        {% endif %}
        {% if success_update %}
            <div class="alert alert-success" role="alert">
                Запись обновлена
            </div>
        {% endif %}
    </div>
    <div class="row">
        <h2 class="mt-4 text-center">Редактирование отделений</h2>
        {% if update %}
            <form id="update_data" method="post">
                    {% csrf_token %}
                    {{form}}
            </form>
        <div>
            <button form="update_data" type="submit" class="btn btn-primary mt-5">Обновить</button>
            <a href="/edit_groups/" class="btn btn-secondary mt-5">Назад</a>
        </div>

        {% else %}
            <button type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#exampleModal">
              Добавить новое отделение
            </button>
            <table class="table table-bordered mt-4">
                <thead>
                <tr>
                  <th scope="col">id</th>
                  <th scope="col">Название</th>
                  <th scope="col">Взвод</th>
                  <th scope="col">Курс</th>
                  <th scope="col" style="width: 50px;">Действие</th>
                </tr>
              </thead>
                <tbody>
            {% for i in departaments %}
            <tr>
              <th>{{i.id}}</th>
              <td>{{i.name}}</td>
              <td>{{i.platoon}}</td>
              <td>{{i.course}}</td>
              <td scope="col">
                  <div class="container">
                      <div class="row">
                            <div class="col-md-6">
                                <a href="{% url 'app:update_group' i.id %}"><i class="fas fa-pencil-alt"></i></a>
                            </div>
                            <div class="col-md-6">
                                <a href="{% url 'app:delete_group' i.id %}"><i class="fas fa-trash"></i></a>
                            </div>
                      </div>
                  </div>
              </td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        {% endif %}

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Новое отделение</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form id="add_form" method="post">
                    {% csrf_token %}
                    {{form}}
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

monitoring/app/templates/edit_platoons.html
{% extends 'base.html' %}

{% block title %}Edit platoons Page{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% if success %}
            <div class="alert alert-success" role="alert">
                Взвод добавлено
            </div>
        {% endif %}
        {% if success_update %}
            <div class="alert alert-success" role="alert">
                Запись обновлена
            </div>
        {% endif %}
    </div>
    <div class="row">
        <h2 class="mt-4 text-center">Редактирование взводов</h2>
        {% if update %}
            <form id="update_data" method="post">
                    {% csrf_token %}
                    {{form}}
            </form>
        <div>
            <button form="update_data" type="submit" class="btn btn-primary mt-5">Обновить</button>
            <a href="/edit_platoons/" class="btn btn-secondary mt-5">Назад</a>
        </div>

        {% else %}
            <button type="button" class="btn btn-primary mt-2" data-toggle="modal" data-target="#exampleModal">
              Добавить новый взвод
            </button>
            <table class="table table-bordered mt-4">
                <thead>
                <tr>
                  <th scope="col">id</th>
                  <th scope="col">Название</th>
                  <th scope="col">Направление</th>
                  <th scope="col" style="width: 50px;">Действие</th>
                </tr>
              </thead>
                <tbody>
            {% for i in departaments %}
            <tr>
              <th>{{i.id}}</th>
              <td>{{i.name}}</td>
              <td>{{i.company}}</td>
              <td scope="col">
                  <div class="container">
                      <div class="row">
                            <div class="col-md-6">
                                <a href="{% url 'app:update_platoon' i.id %}"><i class="fas fa-pencil-alt"></i></a>
                            </div>
                            <div class="col-md-6">
                                <a href="{% url 'app:delete_platoon' i.id %}"><i class="fas fa-trash"></i></a>
                            </div>
                      </div>
                  </div>
              </td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        {% endif %}

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Новый взвод</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form id="add_form" method="post">
                    {% csrf_token %}
                    {{form}}
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button form="add_form" type="submit" class="btn btn-primary">Добавить</button>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

monitoring/app/templates/logout.html
{% extends 'index.html' %}  <!-- Если у вас есть базовый шаблон -->

{% block content %}
    <h2>Logout</h2>
    <p>You have been successfully logged out.</p>
{% endblock %}

monitoring/app/templates/report.html
{% extends 'base.html' %}

{% block title %}Report Page{% endblock %}

{% block content %}
<div class="container mt-5 text-center">
    <h2 class="mb-4">Генерация отчета</h2>

    <!-- Filters -->
    <form class="form-inline mb-4 text-center" method="post" action="{% url 'app:report' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" id="id_name_hidden" name="name_hidden">
    <button type="submit" class="btn btn-primary mt-2">Сгенерировать</button>
    </form>
</div>



<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Получаем элементы по ID
    var endDateInput = document.getElementById('id_end_date');
    var startDateInput = document.getElementById('id_start_date');

    // Проверяем наличие элементов и отсутствие значений
    if (endDateInput && !endDateInput.value) {
      var currentDate = new Date();
      // Устанавливаем значение только в случае отсутствия текущего значения
      endDateInput.value = currentDate.toISOString().split('T')[0];
    }

    if (startDateInput && !startDateInput.value) {
      var currentDate = new Date();
      var startDate = new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1);
      // Устанавливаем значение только в случае отсутствия текущего значения
      startDateInput.value = startDate.toISOString().split('T')[0];
    }
  });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function() {
        $("#id_name").autocomplete({
            source: '{% url 'app:control' %}',
            minLength: 2,
            select: function(event, ui) {
                event.preventDefault();
                $("#id_name").val(ui.item.label);
                $("#id_name_hidden").val(ui.item.value); // Скрытое поле для хранения cadet.pk
            }
        }).autocomplete("widget").addClass("custom-bootstrap-autocomplete");
    });
</script>
{% endblock %}